### PR TITLE
Getting this to build on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by randlem**
This commit fixes the issue that @promorphus was having related to issue #26.  Works on Ubuntu 16.04 with PHP7 installed from apt.

### CODE REVIEW

File: engine/php7-debian.go [hunk 1]
```diff
@@ -7,6 +7,6 @@
 
 package engine
 
-// #cgo CFLAGS: -I/usr/include/php/20151012 -Iinclude/php7 -Isrc/php7
+// #cgo CFLAGS: -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/TSRM -Iinclude/php7 -Isrc/php7
```
Comment (deuill) [inline engine/php7-debian.go]: Could you break these in two lines, as in [php5.go](https://github.com/deuill/go-php/blob/daf6987b14a969e3935127753e0a4cec6c3fd768/engine/php5.go#L5)? Otherwise looks great.

**Comment by deuill** [comment]
@randlem Perfect, thanks for this. Makes complete and total sense, if you can fix the review comments I'll push this ASAP.

**Comment by promorphus** [comment]
Hmm, I've got a slight issue actually. So building this is fine, but then attempting to invoke it causes essentially the same issue. Here's what I'm looking at (again).


```
vagrant@CHANGEME:~/go/src/github.com/deuill/go-php/engine$ go get -tags php7.debian github.com/deuill/go-php
vagrant@CHANGEME:~/go/src/github.com/deuill/go-php/engine$
```

Yeah success!

But then....
```
package main

import php "github.com/deuill/go-php"

func main() {

	script := php.New()
	return
}
```

Go building this gives me....

```
vagrant@CHANGEME:~/go/src/github.onpay.com/parasshah/test$ go build
# github.com/deuill/go-php/engine
../../../github.com/deuill/go-php/engine/context.go:11:23: fatal error: main/php.h: No such file or directory
 // #include <main/php.h>
                       ^
compilation terminated.
```
